// Country list for geo pricing and for a vendor's own profile (ISO-2 + name).
// CA-BC = British Columbia exception, kept because iwopo prices it separately.
//
// This was 27 countries, which meant a vendor in Indonesia, Turkey, Korea or
// Poland could not say where they were — and since their currency defaults from
// this, they could not be quoted correctly either. A country here does not have
// to have its own pricing; unpriced ones fall back to the default row.
export const COUNTRIES = [
  { code: 'default', name: '🌐 Default (USD — all others)' },
  { code: 'CA-BC', name: '🇨🇦 Canada · British Columbia' },
  { code: 'CA', name: '🇨🇦 Canada (rest)' },
  { code: 'US', name: '🇺🇸 United States' },
  { code: 'MX', name: '🇲🇽 Mexico' },

  { code: 'GB', name: '🇬🇧 United Kingdom' },
  { code: 'IE', name: '🇮🇪 Ireland' },
  { code: 'DE', name: '🇩🇪 Germany' },
  { code: 'FR', name: '🇫🇷 France' },
  { code: 'ES', name: '🇪🇸 Spain' },
  { code: 'IT', name: '🇮🇹 Italy' },
  { code: 'NL', name: '🇳🇱 Netherlands' },
  { code: 'BE', name: '🇧🇪 Belgium' },
  { code: 'AT', name: '🇦🇹 Austria' },
  { code: 'PT', name: '🇵🇹 Portugal' },
  { code: 'GR', name: '🇬🇷 Greece' },
  { code: 'CH', name: '🇨🇭 Switzerland' },
  { code: 'SE', name: '🇸🇪 Sweden' },
  { code: 'NO', name: '🇳🇴 Norway' },
  { code: 'DK', name: '🇩🇰 Denmark' },
  { code: 'FI', name: '🇫🇮 Finland' },
  { code: 'IS', name: '🇮🇸 Iceland' },
  { code: 'PL', name: '🇵🇱 Poland' },
  { code: 'CZ', name: '🇨🇿 Czechia' },
  { code: 'HU', name: '🇭🇺 Hungary' },
  { code: 'RO', name: '🇷🇴 Romania' },
  { code: 'BG', name: '🇧🇬 Bulgaria' },
  { code: 'HR', name: '🇭🇷 Croatia' },
  { code: 'RS', name: '🇷🇸 Serbia' },
  { code: 'UA', name: '🇺🇦 Ukraine' },
  { code: 'TR', name: '🇹🇷 Türkiye' },

  { code: 'AE', name: '🇦🇪 UAE' },
  { code: 'SA', name: '🇸🇦 Saudi Arabia' },
  { code: 'QA', name: '🇶🇦 Qatar' },
  { code: 'KW', name: '🇰🇼 Kuwait' },
  { code: 'BH', name: '🇧🇭 Bahrain' },
  { code: 'OM', name: '🇴🇲 Oman' },
  { code: 'JO', name: '🇯🇴 Jordan' },
  { code: 'IL', name: '🇮🇱 Israel' },

  { code: 'IN', name: '🇮🇳 India' },
  { code: 'PK', name: '🇵🇰 Pakistan' },
  { code: 'BD', name: '🇧🇩 Bangladesh' },
  { code: 'LK', name: '🇱🇰 Sri Lanka' },
  { code: 'NP', name: '🇳🇵 Nepal' },
  { code: 'CN', name: '🇨🇳 China' },
  { code: 'HK', name: '🇭🇰 Hong Kong' },
  { code: 'TW', name: '🇹🇼 Taiwan' },
  { code: 'JP', name: '🇯🇵 Japan' },
  { code: 'KR', name: '🇰🇷 South Korea' },
  { code: 'SG', name: '🇸🇬 Singapore' },
  { code: 'MY', name: '🇲🇾 Malaysia' },
  { code: 'ID', name: '🇮🇩 Indonesia' },
  { code: 'TH', name: '🇹🇭 Thailand' },
  { code: 'VN', name: '🇻🇳 Vietnam' },
  { code: 'PH', name: '🇵🇭 Philippines' },

  { code: 'ZA', name: '🇿🇦 South Africa' },
  { code: 'NG', name: '🇳🇬 Nigeria' },
  { code: 'KE', name: '🇰🇪 Kenya' },
  { code: 'GH', name: '🇬🇭 Ghana' },
  { code: 'TZ', name: '🇹🇿 Tanzania' },
  { code: 'UG', name: '🇺🇬 Uganda' },
  { code: 'EG', name: '🇪🇬 Egypt' },
  { code: 'MA', name: '🇲🇦 Morocco' },
  { code: 'TN', name: '🇹🇳 Tunisia' },
  { code: 'MU', name: '🇲🇺 Mauritius' },
  { code: 'CI', name: "🇨🇮 Côte d'Ivoire" },
  { code: 'SN', name: '🇸🇳 Senegal' },
  { code: 'CM', name: '🇨🇲 Cameroon' },

  { code: 'BR', name: '🇧🇷 Brazil' },
  { code: 'AR', name: '🇦🇷 Argentina' },
  { code: 'CL', name: '🇨🇱 Chile' },
  { code: 'CO', name: '🇨🇴 Colombia' },
  { code: 'PE', name: '🇵🇪 Peru' },
  { code: 'UY', name: '🇺🇾 Uruguay' },
  { code: 'DO', name: '🇩🇴 Dominican Republic' },
  { code: 'JM', name: '🇯🇲 Jamaica' },
  { code: 'TT', name: '🇹🇹 Trinidad & Tobago' },

  { code: 'AU', name: '🇦🇺 Australia' },
  { code: 'NZ', name: '🇳🇿 New Zealand' },
  { code: 'FJ', name: '🇫🇯 Fiji' },
];
